### ISSUE TITLE
Training Accuracy 0.0000

### ISSUE THREAD

**Issue by YashRunwal** [mdzalfirdausi/CNN-for-Paderborn-Bearing-Dataset#1]
Hi,

I am using the model given here and training the paderborn dataset. The entire dataset. I am getting the training accuracy as 0.000. Any reasons for that?

**Comment by mdzalfirdausi** [comment]
It's hard to justify what's wrong when I used the model and achieved good accuracy.
can you provide some pictures?
the confusion matrix I got with the model:
![image](https://user-images.githubusercontent.com/79037461/153710150-1b049068-480a-4312-bfc5-a5889bad09e9.png)
